import { afterEach, describe, expect, it, vi } from "vitest";

const { generateTextJSONMock } = vi.hoisted(() => ({
  generateTextJSONMock: vi.fn(),
}));

vi.mock("@/lib/ai/text-client", () => ({
  TEXT_ANALYSIS_BOUNDARY: "DeepSeek text analysis boundary",
  generateTextJSON: generateTextJSONMock,
  hasTextAIApiKey: vi.fn(() => true),
}));

import { defaultScenarioPack } from "@/data/scenario-packs";
import { generateSuggestedAnswer } from "@/lib/ai/suggested-answer";

describe("generateSuggestedAnswer", () => {
  afterEach(() => {
    vi.clearAllMocks();
    vi.unstubAllEnvs();
  });

  it("uses vocabulary generated by the text model for suggested answers", async () => {
    generateTextJSONMock.mockResolvedValueOnce({
      aiQuestion: {
        english:
          "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
      },
      analysis:
        "This enterprise buyer wants a scenario-specific answer rather than a generic pilot answer.",
      responseStrategy: {
        english:
          "Explain the maintenance workflow, then connect hands-free guidance to the buyer's operational use case.",
        chinese:
          "先解释维护流程，再把免手持指导连接到客户的运营使用场景。",
      },
      contextBreakdown: {
        conversationStateZh: "当前对话正在围绕设备维护场景展开。",
        customerQuestionReasonZh: "客户想确认这个方案是否适合远程支持团队。",
        priorUserAnswerZh: "用户前面已经提到要支持现场协作。",
        missingInformationZh: "还缺少客户的维护流程和远程专家参与方式。",
        responseBoundaryZh: "不要承诺材料中没有确认的行业认证或准确率。",
      },
      logicBreakdown: {
        surfaceMeaningZh: "客户在问具体使用方式。",
        customerIntentZh: "客户想判断应用场景是否真实可落地。",
        informationNeededZh: "客户需要了解谁使用、何时使用、如何协作。",
        responseFocusZh: "回应时要聚焦维护工作流和免手持协作。",
      },
      suggestedReplies: [
        {
          english:
            "For maintenance, the field engineer can keep both hands free while following remote expert guidance through the glasses.",
          chinese:
            "在维护场景中，现场工程师可以保持双手操作，同时通过眼镜跟随远程专家指导。",
          reason:
            "It answers the use case directly and turns the scenario into a concrete workflow.",
        },
      ],
      vocabulary: [
        {
          term: "remote expert guidance",
          phonetic: "/rɪˈmoʊt ˈekspɜːrt ˈɡaɪdəns/",
          chinese: "远程专家指导",
          example: "follow remote expert guidance through the glasses",
        },
        {
          term: "field engineer",
          phonetic: "/fiːld ˌendʒɪˈnɪr/",
          chinese: "现场工程师",
          example: "the field engineer can keep both hands free",
        },
      ],
      phrasebookEntry: {
        category: "产品应用场景",
        english:
          "For maintenance, the field engineer can keep both hands free while following remote expert guidance through the glasses.",
        chinese:
          "在维护场景中，现场工程师可以保持双手操作，同时通过眼镜跟随远程专家指导。",
        useCase: "Answer a maintenance scenario question.",
        tags: ["suggested-answer", "live-coaching"],
        source: "review",
        masteryStatus: "needs_practice",
      },
    });
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_model_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual([
      "remote expert guidance",
      "field engineer",
    ]);
    expect(suggestion.vocabulary.map((item) => item.term)).not.toEqual(
      expect.arrayContaining(["workflow fit", "pilot scope"]),
    );
    expect(generateTextJSONMock).toHaveBeenCalledWith(
      expect.objectContaining({
        model: "deepseek-v4-flash",
        schemaName: "suggested answer",
        timeoutMs: 12_000,
        maxRetries: 1,
      }),
    );
  });

  it("filters ordinary model vocabulary and keeps core rescue vocabulary concise", async () => {
    generateTextJSONMock.mockResolvedValueOnce({
      aiQuestion: {
        english:
          "Can you explain how your deployment setup handles security requirements?",
        translationZh: "你能解释你们的部署方案如何处理安全要求吗？",
      },
      analysis:
        "This technical buyer needs a bounded security answer with a concrete next step.",
      responseStrategy: {
        english:
          "Acknowledge the security concern, then propose a technical review around deployment requirements.",
        chinese: "先回应安全顾虑，再建议围绕部署要求进行技术评审。",
      },
      contextBreakdown: {
        conversationStateZh: "当前对话正在进入部署和安全评估。",
        customerQuestionReasonZh: "客户想确认方案是否符合企业安全要求。",
        priorUserAnswerZh: "用户前面还没有解释部署边界。",
        missingInformationZh: "还缺少客户的部署环境和安全要求。",
        responseBoundaryZh: "不要承诺未经材料确认的认证、加密等级或部署能力。",
      },
      logicBreakdown: {
        surfaceMeaningZh: "客户在问部署方案如何满足安全要求。",
        customerIntentZh: "客户想判断是否可以进入技术评估。",
        informationNeededZh: "客户需要部署边界、安全要求和下一步确认方式。",
        responseFocusZh: "回应时要把问题推进到技术评审。",
      },
      suggestedReplies: [
        {
          english:
            "We can first review your deployment requirements with your IT team, then confirm the security scope before the pilot.",
          chinese:
            "我们可以先和你们 IT 团队梳理部署要求，再在试点前确认安全范围。",
          reason:
            "It gives a safe next step without overpromising unsupported security details.",
        },
      ],
      vocabulary: [
        {
          term: "customer",
          phonetic: "/ˈkʌstəmər/",
          chinese: "客户",
          example: "customer",
        },
        {
          term: "business",
          phonetic: "/ˈbɪznəs/",
          chinese: "业务",
          example: "business",
        },
        {
          term: "data",
          phonetic: "/ˈdeɪtə/",
          chinese: "数据",
          example: "data",
        },
        {
          term: "support",
          phonetic: "/səˈpɔːrt/",
          chinese: "支持",
          example: "support",
        },
        {
          term: "team",
          phonetic: "/tiːm/",
          chinese: "团队",
          example: "team",
        },
        {
          term: "product",
          phonetic: "/ˈprɑːdʌkt/",
          chinese: "产品",
          example: "product",
        },
        {
          term: "deployment requirements",
          phonetic: "/dɪˈplɔɪmənt rɪˈkwaɪərmənts/",
          chinese: "部署要求",
          example: "review your deployment requirements",
        },
        {
          term: "technical review",
          phonetic: "/ˈteknɪkəl rɪˈvjuː/",
          chinese: "技术评审",
          example: "propose a technical review",
        },
        {
          term: "security scope",
          phonetic: "/sɪˈkjʊrəti skoʊp/",
          chinese: "安全范围",
          example: "confirm the security scope before the pilot",
        },
        {
          term: "pilot",
          phonetic: "/ˈpaɪlət/",
          chinese: "试点",
          example: "before the pilot",
        },
        {
          term: "on-premise",
          phonetic: "/ɑːn ˈpremɪs/",
          chinese: "本地部署的",
          example: "cloud or on-premise deployment",
        },
      ],
      phrasebookEntry: {
        category: "Objection Handling",
        english:
          "We can first review your deployment requirements with your IT team, then confirm the security scope before the pilot.",
        chinese:
          "我们可以先和你们 IT 团队梳理部署要求，再在试点前确认安全范围。",
        useCase: "Handle a deployment security question.",
        tags: ["suggested-answer", "live-coaching"],
        source: "review",
        masteryStatus: "needs_practice",
      },
    });
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_concise_core_rescue_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "objection_handling",
        mode: "objection_handling",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you explain how your deployment setup handles security requirements?",
        translationZh: "你能解释你们的部署方案如何处理安全要求吗？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    expect(suggestion.vocabulary).toHaveLength(4);
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual([
      "deployment requirements",
      "technical review",
      "security scope",
      "on-premise",
    ]);
    expect(suggestion.vocabulary.map((item) => item.term)).not.toEqual(
      expect.arrayContaining([
        "customer",
        "business",
        "data",
        "support",
        "team",
        "product",
        "pilot",
      ]),
    );
  });

  it("repairs malformed phrasebook entries returned by the text model", async () => {
    generateTextJSONMock.mockResolvedValueOnce({
      aiQuestion: {
        english:
          "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能说明部署选项吗？云端还是本地部署？",
      },
      analysis:
        "This technical buyer needs a bounded deployment answer and a clear next step.",
      responseStrategy: {
        english:
          "Acknowledge the deployment concern, avoid unsupported commitments, and propose an IT review.",
        chinese:
          "先回应客户对部署方式的顾虑，避免未经确认的承诺，再建议进入 IT 评审。",
      },
      contextBreakdown: {
        conversationStateZh: "当前正在讨论部署方式和技术评估边界。",
        customerQuestionReasonZh: "客户想确认方案是否符合企业部署要求。",
        priorUserAnswerZh: "用户前面还没有形成完整回答。",
        missingInformationZh: "还缺少客户 IT 政策和部署偏好。",
        responseBoundaryZh: "不要直接承诺所有部署方式。",
      },
      logicBreakdown: {
        surfaceMeaningZh: "客户在问云端部署还是本地部署。",
        customerIntentZh: "客户想判断 Rokid 是否适合进入技术评估。",
        informationNeededZh: "客户需要部署边界、数据流和 IT 确认方式。",
        responseFocusZh: "回应时要把问题推进到技术评审和需求确认。",
      },
      suggestedReplies: [
        {
          english:
            "We can first review your deployment requirements with your IT team, then confirm whether cloud or on-premise is the right setup.",
          chinese:
            "我们可以先和你们 IT 团队梳理部署要求，再确认云端或本地部署哪一种更合适。",
          reason:
            "It keeps the answer bounded and moves the customer toward a concrete technical review.",
        },
      ],
      vocabulary: [
        {
          term: "deployment requirements",
          phonetic: "/dɪˈplɔɪmənt rɪˈkwaɪərmənts/",
          chinese: "部署要求",
          example: "review your deployment requirements",
        },
        {
          term: "on-premise",
          phonetic: "/ɑːn ˈpremɪs/",
          chinese: "本地部署的",
          example: "cloud or on-premise",
        },
      ],
      phrasebookEntry: {
        category: "Technical Decision",
        tags: ["suggested-answer"],
        source: "review",
        masteryStatus: "needs_practice",
      },
    });
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_malformed_phrasebook",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能说明部署选项吗？云端还是本地部署？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    expect(suggestion.phrasebookEntry).toMatchObject({
      category: "Objection Handling",
      english:
        "We can first review your deployment requirements with your IT team, then confirm whether cloud or on-premise is the right setup.",
      chinese:
        "我们可以先和你们 IT 团队梳理部署要求，再确认云端或本地部署哪一种更合适。",
      source: "review",
      masteryStatus: "needs_practice",
    });
    expect(suggestion.phrasebookEntry.tags).toEqual(
      expect.arrayContaining([
        "suggested-answer",
        "live-coaching",
        "technical_lead",
      ]),
    );
  });

  it("does not return a canned core rescue answer when the production model fails", async () => {
    generateTextJSONMock.mockRejectedValueOnce(new Error("model unavailable"));
    vi.stubEnv("NODE_ENV", "production");

    await expect(
      generateSuggestedAnswer({
        practiceSession: {
          id: "session_suggested_fallback",
          scenarioPackId: "rokid-overseas-sales",
          goalId: "customer_qa",
          mode: "customer_qa",
          personaId: "technical_lead",
          voicePackId: "charon-informative",
          materialId: undefined,
          prepCardId: undefined,
          difficulty: "normal",
          trainingFocus: ["privacy and security"],
          focusTags: ["隐私安全"],
          sourceObjectionId: undefined,
          status: "active",
          createdAt: new Date().toISOString(),
        },
        persona: defaultScenarioPack.personas.find(
          (persona) => persona.id === "technical_lead",
        )!,
        latestAiTurn: {
          speaker: "ai_customer",
          text: "Can you detail how data is encrypted both at rest and in transit?",
          translationZh: "你能详细说明数据在静态和传输过程中如何加密吗？",
          timestamp: 0,
          metadata: {},
        },
        transcriptTurns: [],
      }),
    ).rejects.toThrow("建议回答 AI 生成失败");
    expect(generateTextJSONMock).toHaveBeenCalledWith(
      expect.objectContaining({
        schemaName: "suggested answer",
        timeoutMs: 12_000,
        maxRetries: 1,
      }),
    );
  });

  it("derives fallback vocabulary from the current question instead of fixed defaults", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_dynamic_fallback_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      mockMode: true,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    expect(suggestion.vocabulary.length).toBeGreaterThanOrEqual(2);
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual(
      expect.arrayContaining(["remote support team", "equipment maintenance"]),
    );
    expect(suggestion.vocabulary.map((item) => item.term)).not.toEqual(
      expect.arrayContaining(["workflow fit", "pilot scope"]),
    );
  });

  it("does not turn conversational filler chunks into fallback vocabulary", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_no_filler_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      mockMode: true,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Certainly, I was asking which customer segment you are targeting first.",
        translationZh: "当然，我是在问你们优先面向哪个客户细分群体。",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    const terms = suggestion.vocabulary.map((item) => item.term);

    expect(terms).toEqual(expect.arrayContaining(["customer segment"]));
    expect(terms).not.toEqual(
      expect.arrayContaining([
        "certainly i was",
        "i was asking",
        "was asking which",
        "asking which customer",
        "customer segment you",
      ]),
    );
    suggestion.vocabulary.forEach((item) => {
      expect(item.chinese).not.toMatch(/^[a-z]+$/i);
    });
  });

  it("provides at least two vocabulary items for deployment questions", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_deployment_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能解释一下部署选项吗？云部署还是本地部署？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    expect(suggestion.vocabulary.length).toBeGreaterThanOrEqual(2);
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual(
      expect.arrayContaining(["deployment options", "on-premise"]),
    );
  });

  it("uses recent transcript turns to explain the answer context", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_context_breakdown",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能解释一下部署选项吗？云部署还是本地部署？",
        timestamp: 18,
        metadata: {},
      },
      transcriptTurns: [
        {
          speaker: "ai_customer",
          text: "What is your usual deployment model?",
          timestamp: 0,
          metadata: {},
        },
        {
          speaker: "user",
          text: "Let me check with our IT team first.",
          timestamp: 8,
          metadata: {},
        },
      ],
    });

    expect(suggestion.contextBreakdown).toMatchObject({
      conversationStateZh: expect.stringContaining("部署"),
      priorUserAnswerZh: expect.stringContaining("IT team"),
      missingInformationZh: expect.stringContaining("部署"),
      responseBoundaryZh: expect.stringContaining("承诺"),
    });
  });
});
