import { describe, expect, it, vi } from "vitest";

const { generateTextJSONMock } = vi.hoisted(() => ({
  generateTextJSONMock: vi.fn(),
}));

vi.mock("@/lib/ai/text-client", () => ({
  TEXT_ANALYSIS_BOUNDARY: "DeepSeek text analysis boundary",
  generateTextJSON: generateTextJSONMock,
  hasTextAIApiKey: vi.fn(() => true),
}));

import { defaultScenarioPack } from "@/data/scenario-packs";
import { generateSuggestedAnswer } from "@/lib/ai/suggested-answer";

describe("generateSuggestedAnswer", () => {
  it("uses vocabulary generated by the text model for suggested answers", async () => {
    generateTextJSONMock.mockResolvedValueOnce({
      aiQuestion: {
        english:
          "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
      },
      analysis:
        "This enterprise buyer wants a scenario-specific answer rather than a generic pilot answer.",
      responseStrategy: {
        english:
          "Explain the maintenance workflow, then connect hands-free guidance to the buyer's operational use case.",
        chinese:
          "先解释维护流程，再把免手持指导连接到客户的运营使用场景。",
      },
      contextBreakdown: {
        conversationStateZh: "当前对话正在围绕设备维护场景展开。",
        customerQuestionReasonZh: "客户想确认这个方案是否适合远程支持团队。",
        priorUserAnswerZh: "用户前面已经提到要支持现场协作。",
        missingInformationZh: "还缺少客户的维护流程和远程专家参与方式。",
        responseBoundaryZh: "不要承诺材料中没有确认的行业认证或准确率。",
      },
      logicBreakdown: {
        surfaceMeaningZh: "客户在问具体使用方式。",
        customerIntentZh: "客户想判断应用场景是否真实可落地。",
        informationNeededZh: "客户需要了解谁使用、何时使用、如何协作。",
        responseFocusZh: "回应时要聚焦维护工作流和免手持协作。",
      },
      suggestedReplies: [
        {
          english:
            "For maintenance, the field engineer can keep both hands free while following remote expert guidance through the glasses.",
          chinese:
            "在维护场景中，现场工程师可以保持双手操作，同时通过眼镜跟随远程专家指导。",
          reason:
            "It answers the use case directly and turns the scenario into a concrete workflow.",
        },
      ],
      vocabulary: [
        {
          term: "remote expert guidance",
          phonetic: "/rɪˈmoʊt ˈekspɜːrt ˈɡaɪdəns/",
          chinese: "远程专家指导",
          example: "follow remote expert guidance through the glasses",
        },
        {
          term: "field engineer",
          phonetic: "/fiːld ˌendʒɪˈnɪr/",
          chinese: "现场工程师",
          example: "the field engineer can keep both hands free",
        },
      ],
      phrasebookEntry: {
        category: "产品应用场景",
        english:
          "For maintenance, the field engineer can keep both hands free while following remote expert guidance through the glasses.",
        chinese:
          "在维护场景中，现场工程师可以保持双手操作，同时通过眼镜跟随远程专家指导。",
        useCase: "Answer a maintenance scenario question.",
        tags: ["suggested-answer", "live-coaching"],
        source: "review",
        masteryStatus: "needs_practice",
      },
    });
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_model_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });
    vi.unstubAllEnvs();

    expect(suggestion.vocabulary.map((item) => item.term)).toEqual([
      "remote expert guidance",
      "field engineer",
    ]);
    expect(suggestion.vocabulary.map((item) => item.term)).not.toEqual(
      expect.arrayContaining(["workflow fit", "pilot scope"]),
    );
  });

  it("falls back to a safe local suggestion when the text model fails", async () => {
    generateTextJSONMock.mockRejectedValueOnce(new Error("model unavailable"));
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_suggested_fallback",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["privacy and security"],
        focusTags: ["隐私安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you detail how data is encrypted both at rest and in transit?",
        translationZh: "你能详细说明数据在静态和传输过程中如何加密吗？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });
    vi.unstubAllEnvs();

    expect(suggestion).toMatchObject({
      id: expect.stringMatching(/^suggestion_/),
      aiQuestion: {
        english: expect.stringContaining("encrypted"),
      },
      responseStrategy: {
        english: expect.stringContaining("technical buyer"),
        chinese: expect.stringContaining("客户"),
      },
      logicBreakdown: {
        surfaceMeaningZh: expect.stringContaining("加密"),
        customerIntentZh: expect.stringContaining("确认"),
        informationNeededZh: expect.stringContaining("数据"),
        responseFocusZh: expect.stringContaining("安全"),
      },
      contextBreakdown: {
        conversationStateZh: expect.stringContaining("安全"),
        customerQuestionReasonZh: expect.stringContaining("客户"),
        priorUserAnswerZh: expect.any(String),
        missingInformationZh: expect.stringContaining("数据"),
        responseBoundaryZh: expect.stringContaining("承诺"),
      },
      suggestedReplies: expect.arrayContaining([
        expect.objectContaining({
          english: expect.stringContaining("security question"),
        }),
      ]),
      phrasebookEntry: {
        tags: expect.arrayContaining(["suggested-answer", "live-coaching"]),
      },
    });
    expect(suggestion.suggestedReplies[0]?.reason).not.toMatch(
      /[\u4e00-\u9fff]/,
    );
    expect(generateTextJSONMock).toHaveBeenCalledWith(
      expect.objectContaining({
        schemaName: "suggested answer",
        timeoutMs: 6000,
      }),
    );
  });

  it("derives fallback vocabulary from the current question instead of fixed defaults", async () => {
    generateTextJSONMock.mockRejectedValueOnce(new Error("model unavailable"));
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_dynamic_fallback_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "How would a remote support team use Rokid glasses during equipment maintenance?",
        translationZh: "远程支持团队如何在设备维护中使用 Rokid 眼镜？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });
    vi.unstubAllEnvs();

    expect(suggestion.vocabulary.length).toBeGreaterThanOrEqual(2);
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual(
      expect.arrayContaining(["remote support team", "equipment maintenance"]),
    );
    expect(suggestion.vocabulary.map((item) => item.term)).not.toEqual(
      expect.arrayContaining(["workflow fit", "pilot scope"]),
    );
  });

  it("does not turn conversational filler chunks into fallback vocabulary", async () => {
    generateTextJSONMock.mockRejectedValueOnce(new Error("model unavailable"));
    vi.stubEnv("NODE_ENV", "production");

    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_no_filler_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "enterprise_buyer",
        voicePackId: "kore-firm",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["application scenarios"],
        focusTags: ["应用场景"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "enterprise_buyer",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Certainly, I was asking which customer segment you are targeting first.",
        translationZh: "当然，我是在问你们优先面向哪个客户细分群体。",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });
    vi.unstubAllEnvs();

    const terms = suggestion.vocabulary.map((item) => item.term);

    expect(terms).toEqual(expect.arrayContaining(["customer segment"]));
    expect(terms).not.toEqual(
      expect.arrayContaining([
        "certainly i was",
        "i was asking",
        "was asking which",
        "asking which customer",
        "customer segment you",
      ]),
    );
    suggestion.vocabulary.forEach((item) => {
      expect(item.chinese).not.toMatch(/^[a-z]+$/i);
    });
  });

  it("provides at least two vocabulary items for deployment questions", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_deployment_vocabulary",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能解释一下部署选项吗？云部署还是本地部署？",
        timestamp: 0,
        metadata: {},
      },
      transcriptTurns: [],
    });

    expect(suggestion.vocabulary.length).toBeGreaterThanOrEqual(2);
    expect(suggestion.vocabulary.map((item) => item.term)).toEqual(
      expect.arrayContaining(["deployment options", "on-premise"]),
    );
  });

  it("uses recent transcript turns to explain the answer context", async () => {
    const suggestion = await generateSuggestedAnswer({
      practiceSession: {
        id: "session_context_breakdown",
        scenarioPackId: "rokid-overseas-sales",
        goalId: "customer_qa",
        mode: "customer_qa",
        personaId: "technical_lead",
        voicePackId: "charon-informative",
        materialId: undefined,
        prepCardId: undefined,
        difficulty: "normal",
        trainingFocus: ["deployment and security"],
        focusTags: ["部署安全"],
        sourceObjectionId: undefined,
        status: "active",
        createdAt: new Date().toISOString(),
      },
      persona: defaultScenarioPack.personas.find(
        (persona) => persona.id === "technical_lead",
      )!,
      latestAiTurn: {
        speaker: "ai_customer",
        text: "Can you clarify the deployment options? Cloud or on-premise?",
        translationZh: "你能解释一下部署选项吗？云部署还是本地部署？",
        timestamp: 18,
        metadata: {},
      },
      transcriptTurns: [
        {
          speaker: "ai_customer",
          text: "What is your usual deployment model?",
          timestamp: 0,
          metadata: {},
        },
        {
          speaker: "user",
          text: "Let me check with our IT team first.",
          timestamp: 8,
          metadata: {},
        },
      ],
    });

    expect(suggestion.contextBreakdown).toMatchObject({
      conversationStateZh: expect.stringContaining("部署"),
      priorUserAnswerZh: expect.stringContaining("IT team"),
      missingInformationZh: expect.stringContaining("部署"),
      responseBoundaryZh: expect.stringContaining("承诺"),
    });
  });
});
